development:
  adapter: mysql2
  encoding: utf8
  database: sokura_development
  pool: 5
  username: root
  password: 
  socket: /tmp/mysql.sock
 
test:
  adapter: mysql2
  encoding: utf8
  database: sokura_test
  pool: 5
  username: root
  password: 
  socket: /tmp/mysql.sock
